### ISSUE TITLE
ReDoS Vulnerability in Package Depedency

### ISSUE THREAD

**Issue by dbohannon** [papandreou/express-processimage#21]
This package includes as a dependency a version of minimatch which has a published ReDoS vulnerability (see https://nodesecurity.io/advisories/118).

- Name: minimatch
- Version: 0.2.14
- Vulnerable: <=3.0.1
- Path: express-processimage_demo@1.0.0 > express-processimage@7.1.1 > jpegtran@1.0.4 > mocha@2.4.5 > glob@3.2.3 > minimatch@0.2.14

This should probably be addressed if the project maintainers are still hardening this package for production use (https://github.com/papandreou/express-processimage/issues/4).

**Comment by papandreou** [comment]
Thanks, fixed in 7.2.0. It was an accident that jpegtran included mocha as a dependency rather than a dev dep.
