### ISSUE TITLE
Sharp resize options no longer work because the chaining-based API has been removed

### ISSUE THREAD

**Issue by papandreou** [papandreou/express-processimage#24]
Peter Müller @Munter 14:11
Is there a way I can pass options to a sharp resize operation in processimage?
http://sharp.dimens.io/en/stable/api-resize/#resize
I'm trying to improve on my antialiasing

Andreas Lind @papandreou 14:12
Hmm, yeah, sharp's slowly transitioning to providing all options to the actual operation method rather than building up state in a bunch of chained methods.
Our bridge to the old API should still work, though: resize=100,200&withoutChromaSubsampling&withoutAdaptiveFiltering&trellisQuantization&overshootDeringing&optimizeScans&withoutEnlargement&ignoreAspectRatio&interpolateWith=bilinear
Oh, looks like some of it was removed for 0.16, bugger:
* Remove deprecated interpolateWith method - use resize(w, h, { interpolator: ... })
  [#310](https://github.com/lovell/sharp/issues/310)
And for 0.17:
* Deprecate the following output format "option" functions:
    quality, progressive, compressionLevel, withoutAdaptiveFiltering,
    withoutChromaSubsampling, trellisQuantisation, trellisQuantization,
    overshootDeringing, optimiseScans and optimizeScans.
  Access to these is now via output format functions, for example `quality(n)`
    is now `jpeg({quality: n})` and/or `webp({quality: n})`.
dammit
So we'll need to emulate the old API or rethink it :worried:

Peter Müller @Munter 14:19
alright. I doubt I would be able to get really good results with it anyway. This whole concept of auto generated favicons in all sizes without actually doing the pixel snapping on the svg rasterization sucks

Andreas Lind @papandreou 14:19
It's a shame, because the chaining-based API lent itself really well to a query-string based stream of instructions
Hrm, okay
Still, it would be nice to re-enable those features
You can roll back to express-processimage 5.11.0 (pre-sharp 0.16) if you'd still like to try it out

**Comment by alexjeffburke** [comment]
The migration to `impro` has fixed this - query strings supplied to this module are converted to a form understood by that module which applies the correct options on the image type if required.
