### ISSUE TITLE
if i want to process the external server image ?? 

### ISSUE THREAD

**Issue by pradeeprohith** [papandreou/express-processimage#28]
http://localhost:1337/bigImage.png?resize=400,300

rather than using the local image how to resize the external server image

**Comment by papandreou** [comment]
Assuming `bigImage.jpg` lives at `https://externalhost.com/foo/bigImage.jpg` you could accomplish this by adding a piece of proxying middleware after express-processimage (untested):

```js
const proxy = require('http-proxy-middleware');

app.use('/externalImages', express()
  .use(require('express-processimage')())
  .use(proxy({target: 'https://externalhost.com/foo'}));
```

Then http://localhost:1337/externalImages/bigImage.png?resize=400,300 ought to work. Is that what you had in mind?

**Comment by ppradeep65502** [comment]
but i am getting another issue while using 
"Router.use() requires a middle-ware function but got a Object"

**Comment by papandreou** [comment]
Hmm, sounds like you're using a really old version of express? Could you try upgrading to 4.x?

**Comment by pradeeprohith** [comment]
No , i have used the latest version only 
the version of express is  "express": "^4.16.2"

**Comment by papandreou** [comment]
Ah, is `app` an `express.Router` instance? I assumed it would be an express app:

```js
const express = require('express');
const proxy = require('http-proxy-middleware');
const app = express();

app.use('/externalImages', express()
  .use(require('express-processimage')())
  .use(proxy({target: 'https://externalhost.com/foo'}));
```

**Comment by pradeeprohith** [comment]
Thnq i got it  :+1:
