### ISSUE TITLE
how to resize the image based in the height ??

### ISSUE THREAD

**Issue by pradeeprohith** [papandreou/express-processimage#29]
http://localhost:1000/bigImage.png?resize=400,300

This will resize based on the width and height 

if i want to resize only with the height ?
and also tell me the methods that will use in this on the fly

**Comment by papandreou** [comment]
http://localhost:1000/bigImage.png?resize=,300 will set the height to 300 and set the width proportionally :)

**Comment by pradeeprohith** [comment]
Thnq got it  :+1:
