### ISSUE TITLE
.ICO file resize throws 500 Internal Server Error

### ISSUE THREAD

**Issue by ashish-soni** [papandreou/express-processimage#52]
Resize of .ICO files are throwing http error 500, because sharp does not support it and gm also support only read operation of .ico file.  

http://saladelana.nl/____impro/1/onewebmedia/faviconsal.ico?etag=%2247e-587d003b%22&sourceContentType=image%2Fvnd.microsoft.icon&resize=16,16&format=ico

Is it possible to use gm module to convert .ico to .png and perfrom resize operation?

I tried but the issue is that sourceContentType given in querystring is ignored and goes inside leftOverQueryStringFragments and getMockFileNameForContentType returns undefined.

Operations: 
[ { sourceContentType: undefined,
    name: 'png',
    args: [],
    usedQueryStringFragment: 'png' },
  { sourceContentType: 'image/png',
    name: 'resize',
    args: [ 12, 12 ]

If code can make first operation's sourceContentType to image/vnd.microsoft.icon then it works with below url.

http://saladelana.nl/____impro/1/onewebmedia/faviconsal.ico?gm&png&etag=%2247e-587d003b%22&sourceContentType=image%2Fvnd.microsoft.icon&resize=16,16&format=ico

Is this way correct or am I missing something?

**Comment by papandreou** [comment]
Hey Ashish, long time no see!

Yeah, this is a missing feature. It was also a problem in another product that uses this module :). I think there's even an issue about it in a tracker that I no longer have access to, maybe Asana somewhere under "Impro"? Would be helpful if you could find that and copy the information it in here? I'm fairly sure I did some initial research.

**Comment by ashish-soni** [comment]
I am good, how about you?
Sure, I will try to find info in asana and put it here.

**Comment by ashish-soni** [comment]
[0001-Fix-for-.ICO-file-resize-throwing-500-error.patch.txt](https://github.com/papandreou/express-processimage/files/2249756/0001-Fix-for-.ICO-file-resize-throwing-500-error.patch.txt)

Hi @papandreou 
 
I have attached patch for this fix. It looks safe to me. 

If you think, it is safe to merge, can you please do the needful?

**Comment by ashish-onecom** [comment]
I have added pull request and test too.

**Comment by gustavnikolaj** [comment]
The fix to the bug mentioned here was merged and released in 8.0.1 after #53 being merged.
